blueprint:
  name: Water leak → Push + HA bell notification (device picker)
  description: Sends push notifications to selected Mobile App devices and creates a Home Assistant notification (bell icon).
  domain: automation

  input:
    water_sensors:
      name: Water leak sensors
      selector:
        entity:
          multiple: true
          filter:
            - device_class: moisture

    notify_devices:
      name: Devices to notify
      description: Select phones/tablets from the Mobile App integration
      selector:
        device:
          integration: mobile_app
          multiple: true

    send_cleared:
      name: Notify when cleared (sensor OFF)
      default: true
      selector:
        boolean: {}

    send_offline:
      name: Notify when sensor becomes unavailable/unknown
      default: true
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input water_sensors

variables:
  send_cleared: !input send_cleared
  send_offline: !input send_offline
  ent: "{{ trigger.entity_id }}"
  sensor_name: "{{ state_attr(ent, 'friendly_name') or ent }}"
  area: "{{ area_name(ent) }}"
  where_text: "{{ (' in ' ~ area) if area else '' }}"

action:
  - choose:
      # Leak detected: off -> on
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'off'
                 and trigger.to_state.state == 'on' }}
        sequence:
          - action: persistent_notification.create
            data:
              title: "Water leak detected!"
              message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
          - repeat:
              for_each: !input notify_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Water leak detected!"
                    message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:home-flood"
                      color: "red"
                      ttl: 0
                      priority: high

      # Leak cleared: on -> off (optional)
      - conditions:
          - condition: template
            value_template: >
              {{ send_cleared
                 and trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'on'
                 and trigger.to_state.state == 'off' }}
        sequence:
          - action: persistent_notification.create
            data:
              title: "Water leak cleared"
              message: "{{ sensor_name }}{{ where_text }} is dry again."
          - repeat:
              for_each: !input notify_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Water leak cleared"
                    message: "{{ sensor_name }}{{ where_text }} is dry again."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:water-check"
                      color: "green"

      # Sensor offline/unknown (optional)
      - conditions:
          - condition: template
            value_template: >
              {{ send_offline
                 and trigger.to_state is not none
                 and trigger.to_state.state in ['unavailable','unknown'] }}
        sequence:
          - action: persistent_notification.create
            data:
              title: "Leak sensor offline"
              message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
          - repeat:
              for_each: !input notify_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Leak sensor offline"
                    message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                    data:
                      tag: "water-leak-offline-{{ ent | slugify }}"
                      notification_icon: "mdi:water-off"
                      color: "gray"

    default: []
