blueprint:
  name: Water leak → Per-event alarm toggles + HA bell status
  description: Choose alarm-style pushes per event type for a selected set of devices, while other devices always receive normal pushes. Also updates a single HA bell notification via notification_id.
  domain: automation

  input:
    water_sensors:
      name: Water leak sensors
      selector:
        entity:
          multiple: true
          filter:
            - device_class: moisture

    alarm_devices:
      name: Alarm-capable devices
      description: Devices that can receive alarm-style notifications (e.g. Pixel 8)
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    alarm_on_detected:
      name: "ALARM: Leak detected"
      default: true
      selector:
        boolean: {}

    alarm_on_cleared:
      name: "ALARM: Leak cleared"
      default: false
      selector:
        boolean: {}

    alarm_on_offline:
      name: "ALARM: Sensor offline"
      default: false
      selector:
        boolean: {}

    normal_devices:
      name: Normal push devices
      description: Devices that should always receive normal push (e.g. Lenovo tablet / iPad)
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    ha_notification_id:
      name: HA notification_id
      description: Updates the same HA bell notification instead of stacking.
      default: water_leak_status
      selector:
        text: {}

    send_cleared:
      name: Notify when cleared (sensor OFF)
      default: true
      selector:
        boolean: {}

    send_offline:
      name: Notify when sensor becomes unavailable/unknown
      default: true
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input water_sensors

variables:
  send_cleared: !input send_cleared
  send_offline: !input send_offline
  ha_notification_id: !input ha_notification_id

  alarm_on_detected: !input alarm_on_detected
  alarm_on_cleared: !input alarm_on_cleared
  alarm_on_offline: !input alarm_on_offline

  ent: "{{ trigger.entity_id }}"
  sensor_name: "{{ state_attr(ent, 'friendly_name') or ent }}"
  area: "{{ area_name(ent) }}"
  where_text: "{{ (' in ' ~ area) if area else '' }}"

action:
  - choose:
      # =========================
      # Leak detected: off -> on
      # =========================
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'off'
                 and trigger.to_state.state == 'on' }}
        sequence:
          - action: persistent_notification.create
            data:
              notification_id: "{{ ha_notification_id }}"
              title: "🚨 Water leak detected!"
              message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."

          # Alarm-capable devices: alarm OR normal based on checkbox
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ alarm_on_detected }}"
                sequence:
                  - repeat:
                      for_each: !input alarm_devices
                      sequence:
                        - variables:
                            svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                        - service: "{{ svc }}"
                          data:
                            title: "🚨 Water leak detected!"
                            message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                            data:
                              tag: "water-leak-{{ ent | slugify }}"
                              notification_icon: "mdi:home-flood"
                              color: "red"
                              ttl: 0
                              priority: high
                              channel: alarm_stream
                              media_stream: alarm_stream_max
            default:
              - repeat:
                  for_each: !input alarm_devices
                  sequence:
                    - variables:
                        svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                    - service: "{{ svc }}"
                      data:
                        title: "Water leak detected!"
                        message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                        data:
                          tag: "water-leak-{{ ent | slugify }}"
                          notification_icon: "mdi:home-flood"
                          color: "red"

          # Normal devices: always normal
          - repeat:
              for_each: !input normal_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Water leak detected!"
                    message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:home-flood"
                      color: "red"

      # =========================
      # Leak cleared: on -> off
      # =========================
      - conditions:
          - condition: template
            value_template: >
              {{ send_cleared
                 and trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'on'
                 and trigger.to_state.state == 'off' }}
        sequence:
          - action: persistent_notification.create
            data:
              notification_id: "{{ ha_notification_id }}"
              title: "✅ Water leak cleared"
              message: "{{ sensor_name }}{{ where_text }} is dry again."

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ alarm_on_cleared }}"
                sequence:
                  - repeat:
                      for_each: !input alarm_devices
                      sequence:
                        - variables:
                            svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                        - service: "{{ svc }}"
                          data:
                            title: "✅ Water leak cleared"
                            message: "{{ sensor_name }}{{ where_text }} is dry again."
                            data:
                              tag: "water-leak-{{ ent | slugify }}"
                              notification_icon: "mdi:water-check"
                              color: "green"
                              ttl: 0
                              priority: high
                              channel: alarm_stream
                              media_stream: alarm_stream_max
            default:
              - repeat:
                  for_each: !input alarm_devices
                  sequence:
                    - variables:
                        svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                    - service: "{{ svc }}"
                      data:
                        title: "Water leak cleared"
                        message: "{{ sensor_name }}{{ where_text }} is dry again."
                        data:
                          tag: "water-leak-{{ ent | slugify }}"
                          notification_icon: "mdi:water-check"
                          color: "green"

          - repeat:
              for_each: !input normal_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Water leak cleared"
                    message: "{{ sensor_name }}{{ where_text }} is dry again."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:water-check"
                      color: "green"

      # =========================
      # Sensor offline/unknown
      # =========================
      - conditions:
          - condition: template
            value_template: >
              {{ send_offline
                 and trigger.to_state is not none
                 and trigger.to_state.state in ['unavailable','unknown'] }}
        sequence:
          - action: persistent_notification.create
            data:
              notification_id: "{{ ha_notification_id }}"
              title: "⚠️ Leak sensor offline"
              message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ alarm_on_offline }}"
                sequence:
                  - repeat:
                      for_each: !input alarm_devices
                      sequence:
                        - variables:
                            svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                        - service: "{{ svc }}"
                          data:
                            title: "⚠️ Leak sensor offline"
                            message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                            data:
                              tag: "water-leak-offline-{{ ent | slugify }}"
                              notification_icon: "mdi:water-off"
                              color: "gray"
                              ttl: 0
                              priority: high
                              channel: alarm_stream
                              media_stream: alarm_stream_max
            default:
              - repeat:
                  for_each: !input alarm_devices
                  sequence:
                    - variables:
                        svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                    - service: "{{ svc }}"
                      data:
                        title: "Leak sensor offline"
                        message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                        data:
                          tag: "water-leak-offline-{{ ent | slugify }}"
                          notification_icon: "mdi:water-off"
                          color: "gray"

          - repeat:
              for_each: !input normal_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Leak sensor offline"
                    message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                    data:
                      tag: "water-leak-offline-{{ ent | slugify }}"
                      notification_icon: "mdi:water-off"
                      color: "gray"

    default: []
