blueprint:
  name: Water leak → Push per-device (Alarm vs Normal) + HA bell status
  description: Sends leak notifications to selected Mobile App devices. Choose which devices get ALARM/DND-bypass style pushes vs normal pushes. Also creates a single updating HA bell notification.
  domain: automation

  input:
    water_sensors:
      name: Water leak sensors
      selector:
        entity:
          multiple: true
          filter:
            - device_class: moisture

    alarm_devices:
      name: Alarm / bypass-DND devices
      description: Devices that should receive loud/urgent alarm-style pushes (e.g. Pixel 8)
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    normal_devices:
      name: Normal push devices
      description: Devices that should receive a normal push notification (e.g. tablets)
      default: []
      selector:
        device:
          integration: mobile_app
          multiple: true

    ha_notification_id:
      name: HA notification_id
      description: Updates the same HA bell notification instead of stacking.
      default: water_leak_status
      selector:
        text: {}

    send_cleared:
      name: Notify when cleared (sensor OFF)
      default: true
      selector:
        boolean: {}

    send_offline:
      name: Notify when sensor becomes unavailable/unknown
      default: true
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input water_sensors

variables:
  send_cleared: !input send_cleared
  send_offline: !input send_offline
  ha_notification_id: !input ha_notification_id

  ent: "{{ trigger.entity_id }}"
  sensor_name: "{{ state_attr(ent, 'friendly_name') or ent }}"
  area: "{{ area_name(ent) }}"
  where_text: "{{ (' in ' ~ area) if area else '' }}"

action:
  - choose:
      # Leak detected: off -> on
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'off'
                 and trigger.to_state.state == 'on' }}
        sequence:
          # HA bell notification (single updating)
          - action: persistent_notification.create
            data:
              notification_id: "{{ ha_notification_id }}"
              title: "🚨 Water leak detected!"
              message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."

          # ALARM devices
          - repeat:
              for_each: !input alarm_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "🚨 Water leak detected!"
                    message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:home-flood"
                      color: "red"
                      ttl: 0
                      priority: high
                      channel: alarm_stream
                      media_stream: alarm_stream_max

          # NORMAL devices
          - repeat:
              for_each: !input normal_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Water leak detected!"
                    message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:home-flood"
                      color: "red"

      # Leak cleared: on -> off
      - conditions:
          - condition: template
            value_template: >
              {{ send_cleared
                 and trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'on'
                 and trigger.to_state.state == 'off' }}
        sequence:
          - action: persistent_notification.create
            data:
              notification_id: "{{ ha_notification_id }}"
              title: "✅ Water leak cleared"
              message: "{{ sensor_name }}{{ where_text }} is dry again."

          - repeat:
              for_each: !input alarm_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "✅ Water leak cleared"
                    message: "{{ sensor_name }}{{ where_text }} is dry again."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:water-check"
                      color: "green"
                      ttl: 0
                      priority: high
                      channel: alarm_stream
                      media_stream: alarm_stream_max

          - repeat:
              for_each: !input normal_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Water leak cleared"
                    message: "{{ sensor_name }}{{ where_text }} is dry again."
                    data:
                      tag: "water-leak-{{ ent | slugify }}"
                      notification_icon: "mdi:water-check"
                      color: "green"

      # Sensor offline/unknown
      - conditions:
          - condition: template
            value_template: >
              {{ send_offline
                 and trigger.to_state is not none
                 and trigger.to_state.state in ['unavailable','unknown'] }}
        sequence:
          - action: persistent_notification.create
            data:
              notification_id: "{{ ha_notification_id }}"
              title: "⚠️ Leak sensor offline"
              message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."

          - repeat:
              for_each: !input alarm_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "⚠️ Leak sensor offline"
                    message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                    data:
                      tag: "water-leak-offline-{{ ent | slugify }}"
                      notification_icon: "mdi:water-off"
                      color: "gray"
                      ttl: 0
                      priority: high
                      channel: alarm_stream
                      media_stream: alarm_stream_max

          - repeat:
              for_each: !input normal_devices
              sequence:
                - variables:
                    svc: "notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}"
                - service: "{{ svc }}"
                  data:
                    title: "Leak sensor offline"
                    message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                    data:
                      tag: "water-leak-offline-{{ ent | slugify }}"
                      notification_icon: "mdi:water-off"
                      color: "gray"

    default: []
