blueprint:
  name: Water leak → Phone notification (device picker, stable)
  description: Notify selected Mobile App devices when a moisture sensor detects water. Uses notify.mobile_app_* derived from the selected device name.
  domain: automation

  input:
    water_sensors:
      name: Water leak sensors
      selector:
        entity:
          multiple: true
          filter:
            - device_class: moisture

    notify_devices:
      name: Devices to notify
      description: Select phones/tablets from the Mobile App integration
      selector:
        device:
          integration: mobile_app
          multiple: true

    send_cleared:
      name: Notify when cleared (sensor OFF)
      default: true
      selector:
        boolean: {}

    send_offline:
      name: Notify when sensor becomes unavailable/unknown
      default: true
      selector:
        boolean: {}

mode: single

trigger:
  - platform: state
    entity_id: !input water_sensors

variables:
  send_cleared: !input send_cleared
  send_offline: !input send_offline

  ent: "{{ trigger.entity_id }}"
  sensor_name: "{{ state_attr(ent, 'friendly_name') or ent }}"
  area: "{{ area_name(ent) }}"
  where_text: "{{ (' in ' ~ area) if area else '' }}"

action:
  - choose:
      # Leak detected: off -> on
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'off'
                 and trigger.to_state.state == 'on' }}
        sequence:
          - repeat:
              for_each: !input notify_devices
              sequence:
                - variables:
                    dev_name: "{{ device_attr(repeat.item, 'name') }}"
                    svc: "mobile_app_{{ dev_name | slugify }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ services.notify[svc] is defined }}"
                      sequence:
                        - service: "notify.{{ svc }}"
                          data:
                            title: "Water leak detected!"
                            message: "{{ sensor_name }}{{ where_text }} detected moisture. Check immediately."
                            data:
                              tag: "water-leak-{{ ent | slugify }}"
                              notification_icon: "mdi:home-flood"
                              color: "red"
                              ttl: 0
                              priority: high
                  default:
                    - service: persistent_notification.create
                      data:
                        title: "Leak notification device mismatch"
                        message: >
                          Could not find notify service notify.{{ svc }} for device "{{ dev_name }}".
                          Check Developer Tools → Actions for the actual notify.mobile_app_* name, or rename the Mobile App device to match.

      # Leak cleared: on -> off (optional)
      - conditions:
          - condition: template
            value_template: >
              {{ send_cleared
                 and trigger.from_state is not none and trigger.to_state is not none
                 and trigger.from_state.state == 'on'
                 and trigger.to_state.state == 'off' }}
        sequence:
          - repeat:
              for_each: !input notify_devices
              sequence:
                - variables:
                    dev_name: "{{ device_attr(repeat.item, 'name') }}"
                    svc: "mobile_app_{{ dev_name | slugify }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ services.notify[svc] is defined }}"
                      sequence:
                        - service: "notify.{{ svc }}"
                          data:
                            title: "Water leak cleared"
                            message: "{{ sensor_name }}{{ where_text }} is dry again."
                            data:
                              tag: "water-leak-{{ ent | slugify }}"
                              notification_icon: "mdi:water-check"
                              color: "green"
                  default:
                    - service: persistent_notification.create
                      data:
                        title: "Leak cleared device mismatch"
                        message: >
                          Could not find notify service notify.{{ svc }} for device "{{ dev_name }}".

      # Sensor offline/unknown (optional)
      - conditions:
          - condition: template
            value_template: >
              {{ send_offline
                 and trigger.to_state is not none
                 and trigger.to_state.state in ['unavailable','unknown'] }}
        sequence:
          - repeat:
              for_each: !input notify_devices
              sequence:
                - variables:
                    dev_name: "{{ device_attr(repeat.item, 'name') }}"
                    svc: "mobile_app_{{ dev_name | slugify }}"
                - choose:
                    - conditions:
                        - condition: template
                          value_template: "{{ services.notify[svc] is defined }}"
                      sequence:
                        - service: "notify.{{ svc }}"
                          data:
                            title: "Leak sensor offline"
                            message: "{{ sensor_name }}{{ where_text }} became {{ trigger.to_state.state }}. Check battery / Zigbee / connectivity."
                            data:
                              tag: "water-leak-offline-{{ ent | slugify }}"
                              notification_icon: "mdi:water-off"
                              color: "gray"
                  default:
                    - service: persistent_notification.create
                      data:
                        title: "Leak offline device mismatch"
                        message: >
                          Could not find notify service notify.{{ svc }} for device "{{ dev_name }}".

    default: []
